### ISSUE TITLE
Question about proposed drbg Blake2X

### ISSUE THREAD

**Issue by Steppenwolfe65** [BLAKE2/BLAKE2#31]
Hey,
Just read the paper (https://blake2.net/blake2x.pdf)  and would like some clarification.
Is there any source code for this? 
The text is a little light on details, but am I to take it that the message is first hashed, and a counter pre-pended to the hash state and this becomes the message input for subsequent generation cycles? 
What purpose does the XOF flag serve?

Thanks,
John

**Comment by sneves** [comment]
This sort of question is better addressed to `blake2@googlegroups.com`, since it does not directly concern this codebase (yet).

To answer your question, there's no source code yet. The counter is not prepended; it is part of the existing parameter block. The XOF value is there to disambiguate existing hashes from BLAKE2X hashes, so that regular BLAKE2 hashes never coincide with BLAKE2X hashes, even in their inner values. Also to disambiguate hashes of size X from hashes of size Y,  so that they don't partially overlap (except in the 2^n-1 case, where this is explicitly supported).

**Comment by Steppenwolfe65** [comment]
Ok, next time to the mailing list. 
So, the XOF flag is just a way of biasing the initial state, and the counter is the node offset in the params. But what about sequential operation? If using say, 2B; where/how would the counter be introduced between expansion cycles, as the node offset is not used in that configuration.
This seems similar to the generate function in my Blake2, only there I restricted it to sequential operation, because I am not entirely sure that a tree hashing implementation is safe for use as a pseudo random generator. 
It's kind of ironic, I was going to rewrite that function today, and came across your paper..
