### ISSUE TITLE
cpuinfo under different architectures

### ISSUE THREAD

**Issue by neheb** [BLAKE2/BLAKE2#4]
I'm trying to get BLAKE2 on MIPSel and while I have compiled b2sum successfully, the bench program seems to be the annoying part. In particular, it's the cpucycles() function. Since this is MIPSel I cannot use the included cpuinfo headers. I tried replacing the asm code with a random integer but that just produced all 0s in the output.

**Comment by noloader** [comment]
> Option (1) essentially defeats the purpose of the bench utility (i.e. no useful timings at all). Option 2. is better, but it's tricky to integrate reliably into a simple makefile build system.

You *may* have another option at the cost of complexity. The option is to ask the user to set a variable in the environment, then read it from the environment. Reading an envar might be an easier problem.

Detecting the CPU frequency from a shell is often as simple as the following. It covers nearly all the non-Windows platforms I test on:

```
# CPU frequency in GHz
CPU_FREQ=0.0
if [ "$IS_LINUX" -ne "0" ] && [ -e "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq" ]; then
	BLAKE2_CPU_FREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
	BLAKE2_CPU_FREQ=$(awk "BEGIN {print $CPU_FREQ/1024/1024}")
elif [ "$IS_DARWIN" -ne "0" ]; then
	BLAKE2_CPU_FREQ=$(sysctl -a 2>/dev/null | $GREP 'hw.cpufrequency' | head -1 | awk '{print $3}')
	BLAKE2_CPU_FREQ=$(awk "BEGIN {print $CPU_FREQ/1024/1024/1024}")
elif [ "$IS_SOLARIS" -ne "0" ]; then
    BLAKE2_CPU_FREQ=$(psrinfo -v 2>/dev/null | $GREP 'MHz' | head -1 | nawk '{print $6}')
    BLAKE2_CPU_FREQ=$(nawk "BEGIN {print $CPU_FREQ/1024}")
fi
```

Then, in the source code, attempt to read `BLAKE2_CPU_FREQ`. If its not set, then use a default value (2.0 GHz?) and warn the user to set `BLAKE2_CPU_FREQ` for accurate results.

On x86/64, use the hi-res counter and warn the user `BLAKE2_CPU_FREQ` is ignored because you have a better source :)

You have to be careful on Linux and ARM. I've come across some Debian distros which *lack* `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`. Also see [How to retrieve CPU frequency when cpufreq is missing under 3.16.0-4-arm64](https://lists.debian.org/debian-arm/2016/06/msg00028.html) on the debian-arm mailing list.
