### ISSUE TITLE
Keyed hash test case for an independent implementation

### ISSUE THREAD

**Issue by piyush-kurur** [BLAKE2/BLAKE2#54]
Hi, I am implementing the blake2b/2s based keyed hashing in the cryptographic library raaz 
https://github.com/piyush-kurur/raaz/tree/mac. The test cases seems to be working except the one for the empty string. Which means that there is some issue with the way null strings is handled in keyed hashing.

The standard says the following: The first block is the key padded with necessary 0-bytes. For an empty string the standard says that it will only compress this block.

1. What should be the length in this case (key size or the block size) ?

2. What should be the value of the finalisation flag. Should it be that of the final block or that of initial blocks.

**Comment by sneves** [comment]
The key behaves as if it was a prefix of the message, and it is _always_ block-sized. In the case of an empty string, this size is 64 (resp. 128) for BLAKE2s (resp. BLAKE2b). Since only the key block is hashed, it should contain the appropriate last-block finalization flags.

The only exception is an unkeyed empty message, which requires a compression call with length = 0.

**Comment by piyush-kurur** [comment]
@sneves Thanks for the prompt reply. I will be pestering you if there is any more problems ;-)

**Comment by piyush-kurur** [comment]
@sneves Things seems to be working now. Thanks
